# Generated by Django 3.1.3 on 2020-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20201130_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='mp3',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
