# Generated by Django 3.1.3 on 2020-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=256)),
                ('singer', models.CharField(max_length=256)),
                ('mp3', models.CharField(max_length=256)),
                ('lrc', models.TextField()),
            ],
        ),
    ]
