# Generated by Django 3.1.3 on 2020-12-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_music1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=256)),
                ('singer', models.CharField(max_length=256)),
                ('mp3', models.CharField(max_length=256)),
                ('lrc', models.TextField()),
                ('headphoto', models.CharField(max_length=256)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
