# Generated by Django 3.1.3 on 2020-12-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_musicweb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicWeb',
            new_name='Mp3',
        ),
    ]
