# Generated by Django 3.1.3 on 2020-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20201205_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mp3',
            old_name='headphoto',
            new_name='hp',
        ),
        migrations.AlterField(
            model_name='mp3',
            name='rank',
            field=models.CharField(max_length=256),
        ),
    ]
