# Generated by Django 3.1.3 on 2020-12-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20201205_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp3',
            name='rank',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
