# Generated by Django 3.1.3 on 2020-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20201205_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=256)),
                ('singer', models.CharField(max_length=256)),
                ('mp3', models.CharField(max_length=256)),
                ('lrc', models.TextField()),
                ('hp', models.CharField(default=None, max_length=256)),
                ('rank', models.CharField(default=None, max_length=256)),
            ],
        ),
    ]
